steps:
  # Install dependencies
  - name: python
    entrypoint: pip
    args: ["install", "-r", "requirements.txt", "--user"]

  # Compile pipeline
  - name: 'python'
    entrypoint: 'python'
    args: ['pipeline.py']
    id: 'compile'

  # Upload compiled pipeline to GCS.
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'final.json', 'gs://demo-account//PipelineOutputs']
    id:  'upload'
    waitFor: ['compile']
timeout: 8000s
options:
  logging: CLOUD_LOGGING_ONLY