repos:

# black code formatter
- repo: https://github.com/ambv/black
  rev: 21.10b0
  hooks:
  - id: black
    args: # arguments to configure black
      - --line-length=88
      - --check

    # language should be local
    language_version: python3.9